config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: "timelines#index"

  resources :profile, only: [:edit, :update, :show, :destory] do
    member do
      get :following, :followers
    end
  end

  resources :timelines

  namespace :api, defaults: { format: :jason } do
    scope 'timelines/:timelines_id' do
      resources :comments, only: [:index, :create, :destory]
      resource :like, only: [:show, :create, :destroy]
    end
  end

  resources :relationships, only: [:create, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/timeline.rb
class Timeline < ApplicationRecord
    belongs_to :user
    has_many_attached :album
    has_many :likes, dependent: :destroy
    has_many :comments, dependent: :destroy

    validates :title, presence: true, length: { maximum: 200 }

    def created_add
        Time.zone.now.yday
    end
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
    before_action :authenticate_user!

    def index
        following_id = current_user.following.pluck(:id)
        @timelines = Timeline.where(user_id: following_id)
        @timelines_ather= Timeline.all
    end
    
    def show
        @timelines = Timeline.find(params[:id])
        @comments = Comment.all
        @profile = Profile.all
    end

    def new
        @user = current_user
        @timelines = @user.timelines.build
    end
    
    def create
        @user = current_user
        @timelines = @user.timelines.build(timelines_params)
        if @timelines.save
            redirect_to timelines_path(@timelines), notice: '保存できたよ'
        else
            flash.now[:error] = '保存に失敗しました'
            render :show
        end
    end

    def destroy
        timelines = current_user.timelines.find(params[:id])
        timelines.destroy!
        redirect_to timelines_path(@timelines), notice: '削除に成功しました'
    end

    private
    def timelines_params
        params.require(:timeline).permit(
            :title,
            album: []
        )
    end


end

app/helpers/timeline_helper.rb
module TimelineHelper
end

app/views/timelines/index.html.haml
.container
    .timeline-camera
        = link_to image_tag( 'photo-camera.png' ), new_timeline_path
    .log_out
        = link_to 'Logout', destroy_user_session_path
    .cards
        - @timelines.each do |timelines|
            .timeline_card#timeline-show{data: {timeline_id: timelines.id}}
                .timeline_user
                    - if timelines.user.profile.nil?
                        =link_to profile_path(timelines.user) do
                            = image_tag timelines.user.avatar_img, class: 'index_avatar'
                    - else
                        = link_to profile_path(timelines.user) do
                            = image_tag timelines.user.avatar_img, class: 'index_avatar'
                    .index_username
                        = timelines.user.username
                        = link_to 'Delete', timeline_path(timelines),data: { method: 'delete', confirm: '削除しますか？' }, class: 'timeline_delete'
                .index_create_at
                    %p= time_ago_in_words(timelines.created_at) + ' ago '
                .img_container 
                    - timelines.album.each_with_index do |album, index|
                        = image_tag album, id: "img_container_album#{index}"
                .timeline_fun
                    -# %input{ type:"hidden", value: timelines.id, class: 'timeline_function'}
                    - if current_user.has_liked?(timelines)
                        .article_heart.active-heart{id: timelines.id}
                            = image_tag 'heart_active.png', class: 'heartimg'
                        .article_heart.hidden.inactive-heart{id: timelines.id}
                            = image_tag 'heart.png', class: 'heartimg'
                    -else
                        .article_heart.inactive-heart{id: timelines.id}
                            = image_tag 'heart.png', class: 'heartimg'
                        .article_heart.hidden.active-heart{id: timelines.id}
                            = image_tag 'heart_active.png', class: 'heartimg'
                    %div.likes_count= timelines.likes.count
                    = link_to timeline_path(timelines.id), class: 'comment_img' do
                        = image_tag 'comment.png'
                    = link_to image_tag( 'share.png' ), 'https://twitter.com/share?=#{/}', class: 'share_img'
                .timelines_title
                    = timelines.title

        - @timelines_ather.each do |timelines|
            .timeline_card#timeline-show{data: {timeline_id: timelines.id}}
                .timeline_user
                    - if timelines.user.profile.nil?
                        =link_to edit_profile_path(timelines.user) do
                            = image_tag timelines.user.avatar_img, class: 'index_avatar'
                    - else
                        = link_to profile_path(timelines.user) do
                            = image_tag timelines.user.avatar_img, class: 'index_avatar'
                    .index_username
                        = timelines.user.username
                        = link_to 'Delete', timeline_path(timelines),data: { method: 'delete', confirm: '削除しますか？' }, class: 'timeline_delete'
                .index_create_at
                    %p= time_ago_in_words(timelines.created_at) + ' ago '
                .img_container 
                    - timelines.album.each_with_index do |album, index|
                        = image_tag album, id: "img_container_album#{index}"
                .timeline_fun
                    -# %input{ type:"hidden", value: timelines.id, class: 'timeline_function'}
                    - if current_user.has_liked?(timelines)
                        .article_heart.active-heart{id: timelines.id}
                            = image_tag 'heart_active.png', class: 'heartimg'
                        .article_heart.hidden.inactive-heart{id: timelines.id}
                            = image_tag 'heart.png', class: 'heartimg'
                    -else
                        .article_heart.inactive-heart{id: timelines.id}
                            = image_tag 'heart.png', class: 'heartimg'
                        .article_heart.hidden.active-heart{id: timelines.id}
                            = image_tag 'heart_active.png', class: 'heartimg'
                    %div.likes_count= timelines.likes.count
                    = link_to timeline_path(timelines.id), class: 'comment_img' do
                        = image_tag 'comment.png'
                    = link_to image_tag( 'share.png' ), 'https://twitter.com/share?=#{/}', class: 'share_img'
                .timelines_title
                    = timelines.title

app/views/timelines/new.html.haml
.container
	.new_action_head
		= link_to 'Cancel', timelines_path, class: 'time_line_cancel'
		%h2.timeline_status Status
	= image_tag @user.avatar_img, class:'timeline_new_avatar'
	%h3.timeline_new_name  #{@user.username}
	= form_with(model:@timelines, url: timelines_path, method: 'post', local: true) do |f|
		%div
			= f.text_field :title, class: 'time_line_text_label', placeholder: 'What`s on your mind?'
		%dvi 
			=f.label :album, '+ Album', class: 'time_line_album_field'
			%div
				= f.file_field :album, multiple: true, class: 'time_line_album_field2'
		%div
			= f.submit "Post", class: 'time_line_submit'

app/views/timelines/show.html.haml
.container
    .yajirusi
        = link_to (image_tag 'yajirusi_left.png'), 'javascript:history.back()'
    .user_name
        %h2 Comments
    .comments-container{id: "#{@timelines.id}"}
    
    .comment_text_area
        .text_area_chil{ data: {timeline_id: @timelines.id, user_id: current_user.id , user_name: current_user.username, user_avatar: current_user.avatar_img}}
            = text_area_tag :comment_content, '', class: 'sm'
        .comment_img_btn
            = image_tag 'comment.png'

= javascript_pack_tag 'comment'